#pragma once

#include "Position.h"
#include "../Enums/NodeShape.h"

/**
 * @struct SpawnInfo
 * @brief Data Transfer Object containing all data needed to create a new enemy.
 *
 * Generated by the SpawnService and consumed by the Game loop to instantiate
 * a concrete Node object.
 */
struct SpawnInfo {
    /** @brief Where the enemy should appear (usually off-screen). */
    Position position;

    /** @brief The visual type/shape of the enemy. */
    NodeShape shape{ NodeShape::Circle };

    /** @brief Normalized X component of the movement vector. */
    float directionX{ 0.0f };

    /** @brief Normalized Y component of the movement vector. */
    float directionY{ 0.0f };
};